package main

// activity_normalizer.go
//
// ActivityNormalizerStep maps any raw company activity string to one of the 18
// canonical sector labels defined in activities_fr.txt.
//
// Canonical labels:
//   Agriculture & Élevage          Mines & Extraction
//   Industrie & Fabrication        Énergie & Environnement
//   BTP & Construction             Commerce & Distribution
//   Automobile & Transports        Logistique & Entreposage
//   Hébergement & Tourisme         Restauration & Alimentation
//   Informatique & Télécoms        Banque & Assurance
//   Immobilier                     Services aux Entreprises (B2B)
//   Services aux Particuliers (B2C) Enseignement & Formation
//   Santé & Bien-être              Culture, Sport & Loisirs
//
// Matching strategy (order matters):
//   1. Exact-key lookup in activityMapping (fast path).
//   2. Case-insensitive substring scan against activityKeywords (covers
//      multi-category strings and minor spelling variants).
//   3. Fallback → "Services aux Entreprises (B2B)".

import (
	"context"
	"strings"

	"github.com/rs/zerolog/log"
)

// =============================================================================
// Canonical label constants
// =============================================================================

const (
	ActAgricultureElevage       = "Agriculture & Élevage"
	ActMinesExtraction          = "Mines & Extraction"
	ActIndustrieFabrication     = "Industrie & Fabrication"
	ActEnergieEnvironnement     = "Énergie & Environnement"
	ActBTPConstruction          = "BTP & Construction"
	ActCommerceDistribution     = "Commerce & Distribution"
	ActAutomobileTransports     = "Automobile & Transports"
	ActLogistiqueEntreposage    = "Logistique & Entreposage"
	ActHebergementTourisme      = "Hébergement & Tourisme"
	ActRestaurationAlimentation = "Restauration & Alimentation"
	ActInformatiqueTelocoms     = "Informatique & Télécoms"
	ActBanqueAssurance          = "Banque & Assurance"
	ActImmobilier               = "Immobilier"
	ActServicesB2B              = "Services aux Entreprises (B2B)"
	ActServicesB2C              = "Services aux Particuliers (B2C)"
	ActEnseignementFormation    = "Enseignement & Formation"
	ActSanteBienEtre            = "Santé & Bien-être"
	ActCultureSportLoisirs      = "Culture, Sport & Loisirs"
)

// =============================================================================
// Static exact-match map  (raw activity → canonical label)
// Generated from companies_raw_beautyfied.json – 864 entries.
// =============================================================================

var activityMapping = map[string]string{
		`ADMINISTRATION, gestion du fret multimodal`: "Logistique & Entreposage",
		`AGENCE IMMOBILIÈRE`: "Immobilier",
		`AIR CONDITIONNING & ELECTRICAL APPLIANCES`: "Automobile & Transports",
		`ARCHITECTE`: "BTP & Construction",
		`Abattoirs et viande en gros`: "Agriculture & Élevage",
		`Accompagnement stratégique, conseil en communication et relations publiques, formations`: "Services aux Entreprises (B2B)",
		`Accueil, conseil et bureau d'étude pour investisseurs`: "Services aux Entreprises (B2B)",
		`Activité minière`: "Mines & Extraction",
		`Adduction d'eau et vrd, Assainissement et canalisations, Assainissement et canalisations`: "Énergie & Environnement",
		`Adduction d'eau et vrd, Assainissement et canalisations, Assainissement et canalisations, Batiments et travaux publics, Briqueteries, Bureaux d'etudes et d'ingenierie, Carrieres, exploitation, Cimenteries, Genie civil, Mines, exploitation, Ouvrages d'art, Routes, Travaux publics et terrassement`: "Mines & Extraction",
		`Administration, Création d'entreprise`: "Services aux Entreprises (B2B)",
		`Administration, Fédération des entreprises du Congo`: "Services aux Entreprises (B2B)",
		`Administration, Office Congolais de Contrôle, Contrôle sanitaire`: "Services aux Entreprises (B2B)",
		`Administration, Office national du tourisme`: "Hébergement & Tourisme",
		`Administration, Ordonnateur national du Fonds Européen de Développement`: "Services aux Entreprises (B2B)",
		`Administration, Régularisation des Marchés Publics`: "Services aux Entreprises (B2B)",
		`Administration, Securite sociale`: "Services aux Entreprises (B2B)",
		`Administrations de l'Economie et des Finances, Ministères`: "Banque & Assurance",
		`Administrations de l'Intérieur, Ministères`: "Culture, Sport & Loisirs",
		`Administrations du tourisme, Ministères`: "Hébergement & Tourisme",
		`Administrations, Agriculture`: "Services aux Entreprises (B2B)",
		`Administrations, Technologie, Numérique`: "Informatique & Télécoms",
		`Aeroports, services, Electricite generale et industrielle, Genie civil, Telecommunications, satellite, Telecommunications et telephonie`: "Énergie & Environnement",
		`Affaires, B2B, Industriel`: "Services aux Entreprises (B2B)",
		`Affichage publicitaire`: "Commerce & Distribution",
		`Africala Technologies Ltd`: "Services aux Entreprises (B2B)",
		`Agence WEB, Créatio de site internet, Hébergement de site internet, Référencement SEO, E-Commerce`: "Hébergement & Tourisme",
		`Agence conseil en communication et publicité`: "Services aux Entreprises (B2B)",
		`Agence de communication`: "Services aux Entreprises (B2B)",
		`Agence de communication, Business, B2B, Annuaire des entreprises`: "Culture, Sport & Loisirs",
		`Agence de mannequin`: "Services aux Particuliers (B2C)",
		`Agence de voyage`: "Hébergement & Tourisme",
		`Agence de voyages et de tourisme`: "Hébergement & Tourisme",
		`Agence de voyages et de tourisme, Fret`: "Hébergement & Tourisme",
		`Agence immobilière`: "Immobilier",
		`Agence maritime`: "Logistique & Entreposage",
		`Agence regroupant les métiers du commerce, des relations publiques, de la gestion de clientèle, de l'événementiel, et du facility management intégré.`: "Commerce & Distribution",
		`Agencement et decoration, Agences de publicite et de communication, Ameublement et mobilier, Audiovisuel, materiels et production, Centrales d'achats, Centres de formation professionnelle, Commerce general, Consultants, Import et export, Imprimeries, Mobilier de bureaux`: "Industrie & Fabrication",
		`Agencement et decoration, Agences de publicite et de communication, Architecture et urbanisme, cabinets, Imprimeries, Informatique, environnement, Marketing, Objets publicitaires`: "Industrie & Fabrication",
		`Agencement et decoration, Ameublement et mobilier`: "Commerce & Distribution",
		`Agencement et decoration, Ameublement et mobilier, Blanchisseries et pressings`: "Services aux Particuliers (B2C)",
		`Agencement et decoration, Ameublement et mobilier, Boutiques, Commerce general, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Agencement et decoration, Ameublement et mobilier, Mobilier de bureaux`: "Commerce & Distribution",
		`Agencement et decoration, Artisanat, antiquaires et galeries d'art, Boutiques`: "Commerce & Distribution",
		`Agencement et decoration, Batiments et travaux publics, Bureaux d'etudes et d'ingenierie`: "BTP & Construction",
		`Agencement et decoration, Boissons, Boutiques, Electro-menager`: "Restauration & Alimentation",
		`Agences de presse et d'information`: "Culture, Sport & Loisirs",
		`Agences de publicite et de communication`: "Services aux Entreprises (B2B)",
		`Agences de publicite et de communication, Badges, fabrication, Equipements de bureaux, Equipements de securite bancaire, Fournitures de bureaux, Informatique, maintenance, Tele-surveillance`: "Informatique & Télécoms",
		`Agences de publicite et de communication, Imprimeries`: "Industrie & Fabrication",
		`Agences de publicite et de communication, Informatique, consultants`: "Informatique & Télécoms",
		`Agences de publicite et de communication, Marketing`: "Services aux Entreprises (B2B)",
		`Agences de voyages`: "Hébergement & Tourisme",
		`Agences en douane, Assurances, Commerce general, Immobilier, agences, Transports aeriens, Transports maritimes`: "Automobile & Transports",
		`Agences en douane, Courriers express, Manutention et entreposage, Transit et consignation, Transports aeriens, Transports ferroviaires, Transports maritimes, Transports routiers`: "Automobile & Transports",
		`Agences en douane, Demenagements, Manutention et entreposage, Manutention portuaire, Transit et consignation, Transports aeriens, Transports internationaux, Transports maritimes, Transports routiers`: "Automobile & Transports",
		`Agences en douane, Manutention et entreposage, Transports aeriens, Transports maritimes`: "Automobile & Transports",
		`Agences en douane, Tourisme, Transit et consignation, Transports aeriens, Transports maritimes, Transports routiers`: "Automobile & Transports",
		`Agences en douane, Transit et consignation`: "Logistique & Entreposage",
		`Agences en douane, Transit et consignation, Transports aeriens, Transports maritimes`: "Automobile & Transports",
		`Agences immobilières`: "Immobilier",
		`Agences maritimes, Courriers express`: "Logistique & Entreposage",
		`Agricole, materiels, Agriculture, equipements et materiels, Agriculture, equipements et materiels, Agriculture, produits, Equipements industriels, Groupes electrogenes`: "Agriculture & Élevage",
		`Agricole, materiels, Agriculture, equipements et materiels, Agriculture, equipements et materiels, Assainissement et canalisations, Assainissement et canalisations, Chimie, produits, Phytosanitaires, produits, Veterinaires, produits`: "Agriculture & Élevage",
		`Agricole, materiels, Agriculture, equipements et materiels, Agriculture, equipements et materiels, Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Batteries et piles, Engins de chantier et materiels, Equipements industriels, Garages, Travaux publics et terrassement, materiels, Vehicules industriels`: "Agriculture & Élevage",
		`Agricole, materiels, Agriculture, equipements et materiels, Agriculture, equipements et materiels, Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Engins de chantier et materiels, Etancheite, Garages, Travaux publics et terrassement, materiels, Vehicules industriels`: "Agriculture & Élevage",
		`Agricole, materiels, Alarmes et surveillance, materiels, Climatisation, Eau, traitement, Electricite, materiels, Electro-menager, Etancheite, Groupes electrogenes, Materiaux de construction, Menuiseries aluminium, Miroiteries et vitreries, Phytosanitaires, produits, Pieces detachees industrielles, Piscines, Plomberie et sanitaires, Portes et fenetres, Quincailleries, Shipchandler`: "Agriculture & Élevage",
		`Agriculture`: "Services aux Entreprises (B2B)",
		`Agriculture, Agro-industrie et Développement durable`: "Agriculture & Élevage",
		`Agriculture, Café`: "Agriculture & Élevage",
		`Agriculture, Coton`: "Agriculture & Élevage",
		`Agriculture, Mines, exploitation, Mines, materiels`: "Agriculture & Élevage",
		`Agriculture, equipements et materiels, Agriculture, equipements et materiels, Electricite, materiels`: "Agriculture & Élevage",
		`Agriculture, prestation de service agricole`: "Agriculture & Élevage",
		`Agriculture, produits`: "Agriculture & Élevage",
		`Agro-alimentaire`: "Agriculture & Élevage",
		`Agro-alimentaire, Agro-industrie, Minoteries`: "Agriculture & Élevage",
		`Agro-industrie`: "Agriculture & Élevage",
		`Agro-industrie, Sucre, fabrication et raffinage`: "Agriculture & Élevage",
		`Alarmes et surveillance, materiels`: "Services aux Entreprises (B2B)",
		`Alarmes et surveillance, materiels, Depannage et maintenance industrielle, Electricite generale et industrielle, Electricite, materiels, Incendie et protection, materiels`: "Énergie & Environnement",
		`Alarmes et surveillance, materiels, Electricite generale et industrielle, Electricite, materiels, Incendie et protection, materiels`: "Énergie & Environnement",
		`Alarmes et surveillance, materiels, Espaces verts et jardins, Gardiennage et securite, Nettoyage industriel`: "Services aux Entreprises (B2B)",
		`Alarmes et surveillance, materiels, Gardiennage et securite, Transports de fonds`: "Culture, Sport & Loisirs",
		`Alimentaire, boucherie, poissonnerie`: "Restauration & Alimentation",
		`Alimentaire, produits`: "Restauration & Alimentation",
		`Alimentaire, produits, Alimentation generale`: "Restauration & Alimentation",
		`Alimentaire, produits, Alimentation generale, Supermarches`: "Restauration & Alimentation",
		`Alimentaire, produits, Chimie, produits, Commerce general, Drogueries, Peinture, Quincailleries`: "Restauration & Alimentation",
		`Alimentaire, produits, Entrepots frigorifiques`: "Restauration & Alimentation",
		`Alimentation generale, Elevage, Supermarches`: "Agriculture & Élevage",
		`Alimentation generale, Salons de the et glaciers, Supermarches`: "Restauration & Alimentation",
		`Alimentation generale, Supermarches`: "Restauration & Alimentation",
		`Allumettes et bougies`: "Industrie & Fabrication",
		`Aluminium, industries, Baches et stores, fabrication, Constructions metalliques, Menuiseries aluminium`: "Industrie & Fabrication",
		`Ambassade`: "Culture, Sport & Loisirs",
		`Ambassade, consulat`: "Culture, Sport & Loisirs",
		`Ambassades, consulats`: "Culture, Sport & Loisirs",
		`Ameublement et mobilier`: "Commerce & Distribution",
		`Ameublement et mobilier, Boutiques, Climatisation, Electricite, materiels, Electro-menager, Electronique, Mobilier de bureaux, Textile`: "Énergie & Environnement",
		`Ameublement et mobilier, Electro-menager`: "Commerce & Distribution",
		`Annuaire des entreprises, Pages jaunes`: "Culture, Sport & Loisirs",
		`Annuaire en ligne des professionnels au Congo Brazzaville`: "Culture, Sport & Loisirs",
		`Annuaire national des entreprises, des professionnels et des commerces de la République Démocratique du Congo`: "Culture, Sport & Loisirs",
		`Antennes paraboliques, equipements, Radio-communication, Radio et television, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Appui à l'initiative entrepreneuriale au Sud Kivu en particulier`: "Services aux Entreprises (B2B)",
		`Architecture`: "Services aux Entreprises (B2B)",
		`Architecture et Urbanisme`: "BTP & Construction",
		`Architecture et urbanisme, cabinets`: "BTP & Construction",
		`Architecture et urbanisme, cabinets, Batiments et travaux publics, Bureaux d'etudes et d'ingenierie, Centres de formation professionnelle, Genie civil, Ouvrages d'art, Routes`: "BTP & Construction",
		`Architecture et urbanisme, cabinets, Bureaux d'etudes et d'ingenierie, Consultants, Expertises maritimes et terrestres`: "BTP & Construction",
		`Articles de bureau,de quincaillerie, d'électricité, produits de beauté`: "Services aux Particuliers (B2C)",
		`Ascenseurs, Chantiers navals, Citernes, metallique et plastique, Constructions metalliques, Engins de chantier et materiels, Gaz industriel, Mecanique, industries, Menuiseries metalliques, Vehicules industriels`: "Industrie & Fabrication",
		`Ascenseurs, Groupes electrogenes`: "Énergie & Environnement",
		`Assainissement et assistance financière`: "Banque & Assurance",
		`Assainissement et canalisations, Assainissement et canalisations`: "Énergie & Environnement",
		`Assistant de l'Adga de l'ICCN`: "Services aux Entreprises (B2B)",
		`Association patronale`: "Services aux Entreprises (B2B)",
		`Associations`: "Services aux Entreprises (B2B)",
		`Associations diverses, amicales, fondation`: "Culture, Sport & Loisirs",
		`Associations humanitaires, d'entraide, d'action sociale`: "Culture, Sport & Loisirs",
		`Assurances`: "Services aux Entreprises (B2B)",
		`Assurances agents généraux, courtiers, sociétés, compagnies, assureurs-conseil`: "Banque & Assurance",
		`Assureurs conseils`: "Banque & Assurance",
		`Assureurs courtiers`: "Banque & Assurance",
		`Audio visuel`: "Services aux Entreprises (B2B)",
		`Audiovisuel & Infographie`: "Culture, Sport & Loisirs",
		`Audiovisuel, Cinéma documentaire, Festival de Bukavu, culture et Tourisme`: "Culture, Sport & Loisirs",
		`Audit, Expert et Expertise comptable, Conseil Juridique et Fiscal, Transactions, Business Advisory`: "Services aux Entreprises (B2B)",
		`Audit, comptabilité et conseil en gestion, expert comptable`: "Services aux Entreprises (B2B)",
		`Audit, gestion comptable, fiscalité, conseil en gestion, établissement de documents juridiques, assistances diverses, expert com`: "Services aux Entreprises (B2B)",
		`Auto écoles`: "Services aux Entreprises (B2B)",
		`Automatisation de la relation client via Intelligence Artificielle (IA) sur WhatsApp et mise en place de systèmes de productivité avec Make. Conception de sites web vitrines professionnels et stratégiques pour la conversion de leads. Agent Freelance basé à Pointe-Noire, spécialisé dans l'efficacité digitale et la croissance automatisée.`: "Informatique & Télécoms",
		`Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires`: "Automobile & Transports",
		`Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Bateaux, fabrication, Chantiers navals, Depannage et maintenance industrielle, Location de voitures, Pneumatiques`: "Automobile & Transports",
		`Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Garages, Vehicules industriels`: "Automobile & Transports",
		`Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Vehicules industriels`: "Automobile & Transports",
		`Automobiles et concessionnaires, Automobiles, pieces detachees et accessoires, Vehicules industriels, Nissan, Toyota`: "Automobile & Transports",
		`Automobiles et concessionnaires, Engins de chantier et materiels, Garages, Vehicules industriels`: "Automobile & Transports",
		`Automobiles, pieces detachees et accessoires`: "Automobile & Transports",
		`Automobiles, pieces detachees et accessoires, Automobiles, voitures d'occasions, Equipements industriels, Location d'engins de chantier, Vehicules industriels`: "Automobile & Transports",
		`Automobiles, pieces detachees et accessoires, Automobiles, voitures d'occasions, Garages`: "Automobile & Transports",
		`Automobiles, pieces detachees et accessoires, Batteries et piles, Materiaux de construction, Pneumatiques, Quincailleries`: "BTP & Construction",
		`Automobiles, pieces detachees et accessoires, Garages`: "Automobile & Transports",
		`Automobiles, pieces detachees et accessoires, Garages, Mecanique generale, Nettoyage automobiles`: "Automobile & Transports",
		`Avitaillement Maritime, Logistique, Gestion Immobilière et Commerce Général`: "Logistique & Entreposage",
		`Avocat`: "Services aux Entreprises (B2B)",
		`Avocat au Barreau de Brazzaville`: "Services aux Entreprises (B2B)",
		`Avocat au Barreau de Pointe-Noire`: "Services aux Entreprises (B2B)",
		`Avocat au Barreau de Pointe-Noire Membre du conseil du Barreau.`: "Services aux Entreprises (B2B)",
		`Avocat au Barreau du Congo Brazzaville`: "Services aux Entreprises (B2B)",
		`Avocat, Juriste, Droit de l'homme, Justice et Magistrature`: "Services aux Entreprises (B2B)",
		`Avocats`: "Services aux Entreprises (B2B)",
		`Avocats, Cabinets juridiques et fiscaux`: "Services aux Entreprises (B2B)",
		`Aéroports et services aéroportuaires`: "Automobile & Transports",
		`B2B, TPE/PME/PMI, croissance industrielle`: "Services aux Entreprises (B2B)",
		`BIOMETRIE ET DATA MANAGEMENT`: "Informatique & Télécoms",
		`BTL,ATL, Création Publicitaire, Design 3D, Production Vidéo,Photographie Pro, Force de Vente`: "Services aux Entreprises (B2B)",
		`Banque`: "Services aux Entreprises (B2B)",
		`Banque, Finance`: "Banque & Assurance",
		`Banque, Finances`: "Banque & Assurance",
		`Banque, Finances, Organismes bancaires`: "Banque & Assurance",
		`Banque, Finances, Transfert de fonds, Transfert d'argent`: "Banque & Assurance",
		`Banques et organismes financiers`: "Banque & Assurance",
		`Banques et organismes financiers, Banques et organismes financiers`: "Banque & Assurance",
		`Banques et organismes financiers, Bureaux de change et transferts de fonds`: "Banque & Assurance",
		`Banques et organismes financiers, Credits et finances`: "Banque & Assurance",
		`Banques, Finances`: "Banque & Assurance",
		`Banques, Finances, Bank`: "Banque & Assurance",
		`Bateaux, fabrication, Citernes, metallique et plastique, Plastique, industries, Plastique, produits`: "Industrie & Fabrication",
		`Batiments et travaux publics, Beton, fabrication, Briqueteries, Bureaux d'etudes et d'ingenierie, Carrelages, Genie civil, Materiaux de construction, Menuiseries aluminium, Menuiseries bois`: "Industrie & Fabrication",
		`Batiments et travaux publics, Beton, fabrication, Bureaux d'etudes et d'ingenierie, Genie civil, Piscines, Routes, Travaux publics et terrassement`: "BTP & Construction",
		`Batiments et travaux publics, Beton, fabrication, Carrieres, exploitation, Equipements industriels, Genie civil, Hydraulique, materiels, Location d'engins de chantier`: "Mines & Extraction",
		`Batiments et travaux publics, Bitume, fabrication, Bureaux d'etudes et d'ingenierie, Cimenteries, Genie civil, Location d'engins de chantier, Routes, Travaux publics et terrassement`: "Énergie & Environnement",
		`Batiments et travaux publics, Equipements industriels, Genie civil`: "BTP & Construction",
		`Batiments et travaux publics, Genie civil, Routes`: "BTP & Construction",
		`Batteries et piles, Garages, Pneumatiques`: "Automobile & Transports",
		`Bijouterie, joaillerie, horlogerie, beauté`: "Services aux Particuliers (B2C)",
		`Bitume, fabrication, Hydrocarbures, distribution, Hydrocarbures, lubrifiants`: "Énergie & Environnement",
		`Blanchisseries et pressings`: "Services aux Particuliers (B2C)",
		`Blog`: "Services aux Entreprises (B2B)",
		`Bois`: "Services aux Entreprises (B2B)",
		`Bois et negoce`: "Commerce & Distribution",
		`Bois, industries, Bois et negoce, Exploitations forestieres, Menuiseries bois, Scieries`: "Industrie & Fabrication",
		`Bois, industries, Electricite generale et industrielle, Electricite, materiels, Exploitations forestieres, Genie civil, Menuiseries bois, Transports urbains`: "Énergie & Environnement",
		`Boisson énergisante`: "Services aux Entreprises (B2B)",
		`Boissons`: "Services aux Entreprises (B2B)",
		`Boissons, Boutiques`: "Restauration & Alimentation",
		`Boissons, Commerce general, Hydrocarbures, distribution, Savonneries, Supermarches, Telecommunications et telephonie`: "Énergie & Environnement",
		`Boissons, jus de fruit`: "Restauration & Alimentation",
		`Boucherie, Poissonnerie`: "Services aux Entreprises (B2B)",
		`Boulangerie, Pain, Pâtisserie`: "Restauration & Alimentation",
		`Boulangeries et patisseries`: "Restauration & Alimentation",
		`Boulangeries et patisseries, Catering, Restaurants et bars, Traiteurs`: "Restauration & Alimentation",
		`Boulangeries et patisseries, Salons de the et glaciers`: "Restauration & Alimentation",
		`Boutiques, Commerce general, Import et export, Quincailleries, Transports internationaux, Transports routiers`: "Automobile & Transports",
		`Boutiques, Pret a porter, gros et detail`: "Commerce & Distribution",
		`Branding | Webdesign | Online marketing`: "Informatique & Télécoms",
		`Bureau d'études d'architecture et de génie civil`: "BTP & Construction",
		`Bureautique`: "Services aux Entreprises (B2B)",
		`Bureautique, Climatisation, Electronique, Equipements de securite bancaire, Fournitures de bureaux, Informatique`: "Informatique & Télécoms",
		`Bureautique, Commerce general, Imprimeries, Objets publicitaires`: "Industrie & Fabrication",
		`Bureautique, Electricite, materiels, Informatique, environnement, Informatique, maintenance, Informatique, reseaux`: "Énergie & Environnement",
		`Bureautique, Electronique, Radio et television`: "Informatique & Télécoms",
		`Bureautique, Equipements de securite bancaire, Traitement de valeurs, materiels`: "Informatique & Télécoms",
		`Bureautique, Informatique`: "Informatique & Télécoms",
		`Bureautique, Informatique, Informatique, environnement, Internet, Radio-communication, Telecommunications, reseaux d'entreprises, Telecommunications et telephonie`: "Énergie & Environnement",
		`Bureautique, Informatique, Informatique, reseaux, Internet, Internet, provider, Radio-communication, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Bureautique, Informatique, Telecommunications, satellite, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Bureautique, Informatique, consultants, environnement, formation, maintenance, Internet`: "Énergie & Environnement",
		`Bureautique, Informatique, formation, Informatique, reseaux, Internet, Internet, provider`: "Informatique & Télécoms",
		`Bureaux d'achats, Diamants et Or`: "Mines & Extraction",
		`Bureaux d'etudes et d'ingenierie`: "BTP & Construction",
		`Bureaux de change et transferts de fonds`: "Banque & Assurance",
		`Business`: "Services aux Entreprises (B2B)",
		`Business center, Fournitures de bureaux, Imprimeries`: "Industrie & Fabrication",
		`Business center, Tourisme`: "Hébergement & Tourisme",
		`Business, Exporter`: "Services aux Entreprises (B2B)",
		`BÂTIMENT & TRAVAUX PUBLICS`: "BTP & Construction",
		`Bâtiment`: "Services aux Entreprises (B2B)",
		`Bâtiment, Construction immobilière, Génie civil`: "BTP & Construction",
		`Bâtiment, Travaux publiques`: "BTP & Construction",
		`CABINET COMPTABLE-AUDIT ET EXPERTISE COMPTABLE`: "Services aux Entreprises (B2B)",
		`CABINET D'ingenierie et de cooperation financière`: "Services aux Entreprises (B2B)",
		`CHARLES`: "Services aux Entreprises (B2B)",
		`COMMUNICATION CELLULAIRE BUREAUTIQUE - INFORMATIQUE`: "Informatique & Télécoms",
		`CONSEIL ET ASSISTANCE EN GESTION FINANCIÈRE`: "Banque & Assurance",
		`CURRAGE POMPAGE FOSSE SEPTIQUE`: "Énergie & Environnement",
		`Cabinet Conseil en Organisation, Management et systeme d'information`: "Services aux Entreprises (B2B)",
		`Cabinet International d'Avocats et des Consultants`: "Services aux Entreprises (B2B)",
		`Cabinets juridiques et fiscaux`: "Services aux Entreprises (B2B)",
		`Cabinets juridiques et fiscaux, Expertises comptables, audits et conseils`: "Services aux Entreprises (B2B)",
		`Cabinets medicaux et medecins`: "Santé & Bien-être",
		`Cabinets medicaux et medecins, Cliniques et hopitaux, Dentistes et cabinets dentaires, Laboratoires d'analyses medicales`: "Santé & Bien-être",
		`Cacao, production et exportation, Cafe, production et exportation`: "Agriculture & Élevage",
		`Caoutchouc, industries, Chimie, industries, Cosmetiques, industries, Medical, materiels, Peinture, Pharmaceutiques, produits, Plastique, industries`: "Industrie & Fabrication",
		`Carrelages, Marbrerie`: "BTP & Construction",
		`Carrières, Exploitation, Matériaux de construction, Bâtiment`: "BTP & Construction",
		`Cartonneries, Emballage et conditionnement, Librairies, papeteries, maisons de la presse, Papier, industries`: "Industrie & Fabrication",
		`Casinos et jeux`: "Culture, Sport & Loisirs",
		`Catering, Hotels, Restaurants et bars, Traiteurs`: "Hébergement & Tourisme",
		`Catering, Restaurants et bars, Traiteurs`: "Restauration & Alimentation",
		`Centre de réhabilitation pour le bonobo`: "Santé & Bien-être",
		`Centres de formation professionnelle`: "Enseignement & Formation",
		`Chaine audio visuel de télévision`: "Culture, Sport & Loisirs",
		`Chantiers navals, Electricite generale et industrielle, Electricite, materiels, Equipements industriels, Groupes electrogenes, Incendie et protection, materiels, Moteurs et pompes, Telecommunications et telephonie`: "Énergie & Environnement",
		`Chaussures, manufactures`: "Industrie & Fabrication",
		`Chemin de Fer, Ports, Chantier Navals, Ports et Transport Fluviaux, Ports Maritimes`: "Automobile & Transports",
		`Chimie, industries, Matelas`: "Industrie & Fabrication",
		`Chimie, industries, Materiaux de construction, Peinture`: "Industrie & Fabrication",
		`Cibold`: "Services aux Entreprises (B2B)",
		`Cimenteries`: "Services aux Entreprises (B2B)",
		`Cinemas et videotheques`: "Culture, Sport & Loisirs",
		`Cinemas et videotheques, Internet`: "Culture, Sport & Loisirs",
		`Citernes, metallique et plastique`: "Services aux Entreprises (B2B)",
		`Citernes, metallique et plastique, Constructions metalliques`: "Industrie & Fabrication",
		`Climatisation, Commerce general, Etancheite, Groupes electrogenes, Moteurs et pompes, Quincailleries`: "Énergie & Environnement",
		`Climatisation, Depannage et maintenance industrielle, Electro-menager, Electronique, Froid industriel`: "Services aux Entreprises (B2B)",
		`Climatisation, Electricite, materiels, Electro-menager, Electronique, Peinture, Plomberie et sanitaires, Quincailleries`: "Énergie & Environnement",
		`Climatisation, Electro-menager, Electronique`: "Services aux Entreprises (B2B)",
		`Cliniques et hôpitaux`: "Services aux Entreprises (B2B)",
		`Club de loisirs / club-house`: "Services aux Entreprises (B2B)",
		`Coiffeurs`: "Services aux Particuliers (B2C)",
		`Comité de Pilotage de la Réforme des Entreprises du Porte-feuille de l'État`: "Services aux Entreprises (B2B)",
		`Commerce`: "Services aux Entreprises (B2B)",
		`Commerce Général - Import-Export - Négoce`: "Commerce & Distribution",
		`Commerce de produit alimentaire`: "Restauration & Alimentation",
		`Commerce exterieur, promotion`: "Commerce & Distribution",
		`Commerce general`: "Commerce & Distribution",
		`Commerce general, Friperies, Import et export, Lait, yaourt et fromage`: "Logistique & Entreposage",
		`Commerce général - Import/Export - Bureautique- Papeterie - Informatique et Consommables - Communication`: "Services aux Entreprises (B2B)",
		`Commerce général et alimentation, quincaillerie, divers`: "Commerce & Distribution",
		`Commerce, eau de source`: "Énergie & Environnement",
		`Commerce/ Prestations`: "Services aux Entreprises (B2B)",
		`Commercialisation des produits pétroliers : hydrocarbures, carburants, lubrifiant`: "Énergie & Environnement",
		`Commercialisation des produits pétroliers Mobil, Esso et Sasol.`: "Énergie & Environnement",
		`Commerçant`: "Services aux Entreprises (B2B)",
		`Communautés religieuses`: "Culture, Sport & Loisirs",
		`Commune de Kalamu`: "Services aux Entreprises (B2B)",
		`Communication`: "Services aux Entreprises (B2B)",
		`Compagnie aérienne`: "Automobile & Transports",
		`Compagnie aérienne, Vols, Voyage, Aviation`: "Automobile & Transports",
		`Compagnies aeriennes`: "Automobile & Transports",
		`Compagnies aeriennes, Transports aeriens`: "Automobile & Transports",
		`Compteuse de billets, calculatrices, machines à écrire`: "Services aux Entreprises (B2B)",
		`Comptoir d'Achat de Matières Précieuses`: "Services aux Entreprises (B2B)",
		`Conception et gestion des sites web et communication sur internet`: "Informatique & Télécoms",
		`Conception web · Design graphique · Service d'impression`: "Informatique & Télécoms",
		`Conception, déploiement et maintenance des réseaux informatiques; Conception, déploiement et maintenance des bases de données`: "Informatique & Télécoms",
		`Concessionnaire automobile`: "Automobile & Transports",
		`Concessions forestières dans la province de l'Equateur`: "Agriculture & Élevage",
		`Conseil & assistance: négoce des matériels et équipement`: "Commerce & Distribution",
		`Conseil en relation client`: "Services aux Entreprises (B2B)",
		`Conseils et Accompagnement des Entreprises en Marketing Publicité et Management!`: "Services aux Entreprises (B2B)",
		`Conseils et formations en communication & événementiel`: "Services aux Entreprises (B2B)",
		`Construction Navale et Métallique. Télécommunication. Représentation Industrielle`: "BTP & Construction",
		`Construction Site Web et Multimédias Services`: "Informatique & Télécoms",
		`Construction générale`: "BTP & Construction",
		`Construction métalliques, Réservoirs Citernes Chaudronnerie`: "BTP & Construction",
		`Construction, Promoteur, Gestion dans l'immobilier`: "BTP & Construction",
		`Constructions metalliques, Materiaux de construction, Peinture, Pieces detachees industrielles, Plastique, industries, Plastique, produits, Quincailleries, Tuyauteries, pvc industries`: "Industrie & Fabrication",
		`Consultant en développement informatique`: "Informatique & Télécoms",
		`Consultants`: "Services aux Entreprises (B2B)",
		`Consultants, Investissements, Mines, recherche`: "Mines & Extraction",
		`Consulting, Organisation, Management`: "Services aux Entreprises (B2B)",
		`Consulting, Web Design, Construction, E-commerce`: "BTP & Construction",
		`Contrôlleur et gestionnaire des passations des marchés publics de la RDC`: "Services aux Entreprises (B2B)",
		`Cosmetiques, industries`: "Industrie & Fabrication",
		`Cosmetiques, industries, Cosmetiques, produits`: "Industrie & Fabrication",
		`Cosmetiques, produits`: "Services aux Particuliers (B2C)",
		`Courriers et colis express toutes destinations`: "Services aux Entreprises (B2B)",
		`Courriers express`: "Logistique & Entreposage",
		`Courriers express - Transferts - Cargo aérien et maritime`: "Logistique & Entreposage",
		`Courriers rapides et petits colis "door to door" en RDC`: "Services aux Entreprises (B2B)",
		`Courtier en travaux`: "BTP & Construction",
		`Credits et finances`: "Services aux Entreprises (B2B)",
		`Création d'entreprise`: "Services aux Entreprises (B2B)",
		`Création de sites web, marketing digital et automatisation des entreprises.`: "Informatique & Télécoms",
		`Création, l'hébergement, le référencement et la maintenance des sites internet. Services de traduction (anglais-français)`: "Hébergement & Tourisme",
		`Cybercafé`: "Services aux Entreprises (B2B)",
		`Cycles et motos, Cycles et motos, industries, Cycles et motos, pieces detachees`: "Automobile & Transports",
		`Cycles et motos, Cycles et motos, industries, Cycles et motos, pieces detachees, Energie solaire, Groupes electrogenes, Moteurs et pompes, Photos et films`: "Énergie & Environnement",
		`DISTRIBUTEUR MATERIEL DE LABORATOIRE`: "Services aux Entreprises (B2B)",
		`Demenagements, Garde meubles, Transit et consignation, Transports internationaux`: "Logistique & Entreposage",
		`Depannage et maintenance industrielle, Electricite generale et industrielle, Electricite, materiels, Groupes electrogenes, Moteurs et pompes`: "Énergie & Environnement",
		`Depannage et maintenance industrielle, Nettoyage industriel, Peintres en batiments et travaux publics`: "BTP & Construction",
		`Diamant, exploitation, Diamant et or`: "Mines & Extraction",
		`Distributeur de matériaux de construction`: "BTP & Construction",
		`Distributeur exclusif YAMAHA moto, moteurs`: "Services aux Entreprises (B2B)",
		`Distributeur exclusif des produits "NATIONAL"  en R.D.C`: "Services aux Entreprises (B2B)",
		`Distributeur officiel de CELTEL`: "Services aux Entreprises (B2B)",
		`Distributeur officiel de LAND ROVER et FORD en R.D.C`: "Services aux Entreprises (B2B)",
		`Distribution de carburants terrestres et aviation,  lubrifiants,`: "Énergie & Environnement",
		`Distribution de vivres surgelés`: "Restauration & Alimentation",
		`Division caoutchouc et dérivés`: "Services aux Entreprises (B2B)",
		`Dépôt pharmaceutique et produits plastiques`: "Services aux Entreprises (B2B)",
		`Détection incendie - Techniques spéciales`: "Services aux Entreprises (B2B)",
		`Développement des services sociaux`: "Services aux Entreprises (B2B)",
		`Développement et test logiciel`: "Informatique & Télécoms",
		`E-commerce`: "Informatique & Télécoms",
		`E-marketing`: "Informatique & Télécoms",
		`ELECTRICITE`: "Services aux Entreprises (B2B)",
		`ETANCHEITE,CONSTRUCTION,REFECTION,ARCHITECTURE,ELECTRICITE,SECUR`: "BTP & Construction",
		`Eau de source MAYO`: "Énergie & Environnement",
		`Ecole conventionnée catholique`: "Services aux Entreprises (B2B)",
		`Ecoles et universites`: "Enseignement & Formation",
		`Editeurs`: "Services aux Entreprises (B2B)",
		`Electricite generale et industrielle`: "Énergie & Environnement",
		`Electricite generale et industrielle, Electricite, materiels`: "Énergie & Environnement",
		`Electricite generale et industrielle, Electricite, materiels, Electronique`: "Énergie & Environnement",
		`Electricite generale et industrielle, Electricite, materiels, Energie`: "Énergie & Environnement",
		`Electricite generale et industrielle, Electricite, materiels, Groupes electrogenes, Moteurs et pompes`: "Énergie & Environnement",
		`Electricite, materiels`: "Énergie & Environnement",
		`Electricite, materiels, Electronique, Radio et television`: "Énergie & Environnement",
		`Electricite, materiels, Materiaux de construction, Pieces detachees industrielles, Quincailleries, Toitures`: "Énergie & Environnement",
		`Electricite, materiels, Materiaux de construction, Plomberie et sanitaires`: "Énergie & Environnement",
		`Electricité, électronique`: "Services aux Entreprises (B2B)",
		`Electro-menager, Import et export, Miroiteries et vitreries, Peinture, Plomberie et sanitaires, Quincailleries`: "BTP & Construction",
		`Electroménager - HI FI - Climatisation`: "Services aux Entreprises (B2B)",
		`Elevage de bovins, porcins et ovins. - Boucherie charcuterie`: "Agriculture & Élevage",
		`Emballage et conditionnement`: "Industrie & Fabrication",
		`Emballage et conditionnement, Imprimeries`: "Industrie & Fabrication",
		`Emballage et conditionnement, Papier, industries`: "Industrie & Fabrication",
		`Emballage, conditionnement`: "Services aux Entreprises (B2B)",
		`Emploi, Job`: "Services aux Entreprises (B2B)",
		`Energie`: "Services aux Entreprises (B2B)",
		`Energie solaire`: "Énergie & Environnement",
		`Energie solaire, Informatique, Informatique, reseaux, Radio-communication`: "Énergie & Environnement",
		`Engins de chantier et materiels, Equipements forestiers, Equipements industriels, Groupes electrogenes, Manutention industrielle, Medical, materiels, Mines, materiels`: "Mines & Extraction",
		`Engins de chantier et materiels, Pneumatiques, Travaux publics et terrassement, materiels, Vehicules industriels`: "BTP & Construction",
		`Engins de chantier et materiels, Vehicules industriels`: "Automobile & Transports",
		`Enseignement maternel, Primaire , secondaire et Humanités`: "Enseignement & Formation",
		`Entreprise de logiciels`: "Informatique & Télécoms",
		`Entreprise specialisée dans l'automatisation industrielle`: "Informatique & Télécoms",
		`Entreprises de bâtiment`: "BTP & Construction",
		`Entreprises de bâtiment, construction`: "BTP & Construction",
		`Entreprises de bâtiment, construction, metal`: "BTP & Construction",
		`Entretien et réparation des véhicules`: "Automobile & Transports",
		`Environnement, Hydrocarbures, distribution, Hydrocarbures, lubrifiants, Hydrocarbures, stockage`: "Énergie & Environnement",
		`Espaces verts et jardins, Fleuristes, Phytosanitaires, traitements`: "Agriculture & Élevage",
		`Etancheite, Import et export, Materiaux de construction, Peintres en batiments et travaux publics`: "BTP & Construction",
		`Expertises comptables, audits et conseils`: "Services aux Entreprises (B2B)",
		`Expertises etudes, communication et conseils`: "Services aux Entreprises (B2B)",
		`Exploitant Matières Précieuses, Mines`: "Services aux Entreprises (B2B)",
		`Exploitation d'huile de palme - Agriculture générale`: "Agriculture & Élevage",
		`Exploitation de diamants bruts au Kasaï oriental`: "Mines & Extraction",
		`Exploitation du cobalt et du cuivre.`: "Mines & Extraction",
		`Exploration, Production, transport & Vente de Petrole`: "Énergie & Environnement",
		`Export quality Tractors and Farm Implements`: "Industrie & Fabrication",
		`Exportation de minerais`: "Mines & Extraction",
		`Externalisation de la Gestion des Ressources Humaines`: "Services aux Entreprises (B2B)",
		`Extraction, Raffinage Et Cokéfaction, Exportation, Extraction de Minerais de Métaux Précieux`: "Mines & Extraction",
		`FABRICANT ALUPHONIE`: "Services aux Entreprises (B2B)",
		`FABRICATION DE CHARBON DE BOIS`: "Industrie & Fabrication",
		`FORMATION ET SENSIBILISATION`: "Enseignement & Formation",
		`FRET AERIEN ET MARITIME  , TOURISM , FINANCE`: "Services aux Entreprises (B2B)",
		`FROID,CLIMATISATION,SECURTE ELECTRONIQUE,SOLUTON INFORMATIQUE`: "Services aux Entreprises (B2B)",
		`Fabrication de boisson alcoolisé, non-alcoolisé et glace alimentaire`: "Industrie & Fabrication",
		`Fabrication de mousses et matelas`: "Industrie & Fabrication",
		`Fabrication de mèches capillaires 100% synthétiques.`: "Industrie & Fabrication",
		`Fabrication de peinture industrielle`: "Industrie & Fabrication",
		`Fabrication de peintures de très bonne qualité.`: "Industrie & Fabrication",
		`Fabrication de plaques d'immatriculation automobiles`: "Industrie & Fabrication",
		`Fabrication de pneus.`: "Industrie & Fabrication",
		`Fabrication des drapeaux publicitaires et des nations`: "Industrie & Fabrication",
		`Fabrication et vente de peinture de bâtiment, Rénovation et réfection de bâtiment Études`: "BTP & Construction",
		`Fabrication industrielle de pagnes africains en coton`: "Services aux Entreprises (B2B)",
		`Fabrication, réparation et vente de bijoux`: "Services aux Entreprises (B2B)",
		`Faciltation des affaires`: "Services aux Entreprises (B2B)",
		`Fast food, Restauration`: "Restauration & Alimentation",
		`Fer et acier, industries, Materiaux de construction, Toles, Tuyauteries, pvc industries`: "Industrie & Fabrication",
		`Filatures et Tissage des fibres`: "Agriculture & Élevage",
		`Fintech / Services financiers`: "Informatique & Télécoms",
		`Fonds des Nations Unies pour la Population`: "Culture, Sport & Loisirs",
		`Forages`: "Services aux Entreprises (B2B)",
		`Formation Professionnelle & Coaching`: "Enseignement & Formation",
		`Formation informatique`: "Services aux Entreprises (B2B)",
		`Formation universitaire`: "Enseignement & Formation",
		`Formation, Logiciels, Nouvelles technologies`: "Informatique & Télécoms",
		`Fournisseur de service de sécurité`: "Services aux Entreprises (B2B)",
		`Fournitures de bureaux, Librairies, papeteries, maisons de la presse`: "Culture, Sport & Loisirs",
		`Froid industriel, Transports fluviaux`: "Automobile & Transports",
		`Féderation Congolaise de Football`: "Culture, Sport & Loisirs",
		`GEOLOCALISATION`: "Informatique & Télécoms",
		`GROUPE ELECTROGENE`: "Énergie & Environnement",
		`GROUPE ELECTROGENE - GENERATORS SETS`: "Énergie & Environnement",
		`Galerie d'exposition d'art traditionnel et contemporain`: "Culture, Sport & Loisirs",
		`Garage automobile toutes marques`: "Services aux Entreprises (B2B)",
		`Garage toutes marques`: "Services aux Entreprises (B2B)",
		`Garages`: "Services aux Entreprises (B2B)",
		`Garages, Peinture`: "Automobile & Transports",
		`Garages, Pneumatiques`: "Automobile & Transports",
		`Garages, Transports en commun, Transports urbains, Vehicules industriels`: "Automobile & Transports",
		`Gardiennage et securite, equipements et materiels`: "Services aux Entreprises (B2B)",
		`Gardiennage, Nettoyage bureau, intérieur véhicule, Jardinage`: "Services aux Entreprises (B2B)",
		`Gestion des communautés dans les médias sociaux.`: "Services aux Entreprises (B2B)",
		`Gestion des risques, sécurité, gardiennage, garde du corps`: "Services aux Entreprises (B2B)",
		`Grande distribution, agro-alimentaire`: "Agriculture & Élevage",
		`Groupes électrogènes toutes puissances avec/sans insonorisation`: "Services aux Entreprises (B2B)",
		`HI-FI, électroménager, quincaillerie`: "Commerce & Distribution",
		`Habillement et divers`: "Services aux Entreprises (B2B)",
		`Hotellerie`: "Hébergement & Tourisme",
		`Hotels`: "Services aux Entreprises (B2B)",
		`Hotels, Restaurants et bars`: "Hébergement & Tourisme",
		`Huileries, Savonneries`: "Agriculture & Élevage",
		`Hydrocarbures`: "Services aux Entreprises (B2B)",
		`Hydrocarbures, Pétrole`: "Énergie & Environnement",
		`Hydrocarbures, lubrifiants`: "Énergie & Environnement",
		`Hydrocarbures, transports, Transports internationaux, Transports routiers`: "Énergie & Environnement",
		`Hôpital, Clinique, Centre hospitalier, Médecine, Soins médicaux, Santé`: "Santé & Bien-être",
		`Hôtel`: "Services aux Entreprises (B2B)",
		`Hôtel, Flat, Motel, Résidence, Chambre`: "Hébergement & Tourisme",
		`Hôtel, Restaurant, Loisir`: "Hébergement & Tourisme",
		`Hôtel, Restauration`: "Hébergement & Tourisme",
		`Hôtel, Restauration, Chambres d'hôtes`: "Hébergement & Tourisme",
		`Hôtel, Tourisme, Flat, Motel, Résidence, Chambre, Palace`: "Hébergement & Tourisme",
		`Hôtel, Tourisme, Flat, Motel, Résidence, Maison d'hôte, Chambre`: "Hébergement & Tourisme",
		`Hôtel, Tourisme, Flat, Motel, Résidence, Maison d'hôte, Chambre, Restaurant, Bar`: "Hébergement & Tourisme",
		`Hôtel, flat, motel, résidence, chambre`: "Hébergement & Tourisme",
		`Hôtel, motel, flat, chambre, résidence Location d'appartements`: "Hébergement & Tourisme",
		`Hôtellerie & Restauration, Flat, Motel, Résidence, Chambre`: "Hébergement & Tourisme",
		`Hôtels`: "Hébergement & Tourisme",
		`Hôtels et Restaurants, Maisons d'hôtes, Chambres d'hôtes, Logement`: "Hébergement & Tourisme",
		`IMPORT EXPORT`: "Services aux Entreprises (B2B)",
		`IMPORT-EXPORT`: "Services aux Entreprises (B2B)",
		`IMPORT-EXPPORT`: "Services aux Entreprises (B2B)",
		`IMPRIMERIE-SERIGRAPHIE-PUBLICITE`: "Industrie & Fabrication",
		`INFORMATIQUE - INTERNET VSAT`: "Informatique & Télécoms",
		`Immobilier`: "Services aux Entreprises (B2B)",
		`Immobilier, Expertise Immobilière, Agence Immobilière`: "Immobilier",
		`Immobilier, agences`: "Immobilier",
		`Immobilier, agences, Immobilier, expertises, Immobilier, gestion`: "Immobilier",
		`Immobillier, Cabinet d'architecture, Batiment`: "Services aux Entreprises (B2B)",
		`Import et export, Manutention et entreposage, Tourisme, Transit et consignation, Transports aeriens, Transports fluviaux, Transports internationaux, Transports maritimes, Transports routiers`: "Automobile & Transports",
		`Importateur concessionnaire des véhicules TATA - MAHINDRA`: "Automobile & Transports",
		`Importateur et concessionnaire des marques TOYOTA et SUZUKI`: "Automobile & Transports",
		`Importateur et concessionnaire des semi-remorques RANDON`: "Automobile & Transports",
		`Importateur exclusif GM en RDC : ISUZU et CHEVROLET`: "Automobile & Transports",
		`Importateur exclusif du matériel télécom KENWOOD pour la R.D.C.`: "Automobile & Transports",
		`Importation et Distribution Véhicules Automobiles et Camions`: "Services aux Entreprises (B2B)",
		`Importation et distribution d'équipements agricoles tropicalisés`: "Agriculture & Élevage",
		`Importation et distribution de colorants plastiques pour PVC, P`: "Services aux Entreprises (B2B)",
		`Importation et distribution de friperie, produits Kerrygold`: "Logistique & Entreposage",
		`Importation et distribution de produits pharmaceutiques`: "Santé & Bien-être",
		`Importation et distribution pharmaceutique`: "Logistique & Entreposage",
		`Importation et vente de véhicules`: "Logistique & Entreposage",
		`Importation, Electricité, Habillement, Transport`: "Culture, Sport & Loisirs",
		`Importation, distribution et service après-vente, Cycles et motos, Cycles et motos, pieces detachees, Eau, traitement, Energie, Energie solaire, Equipements industriels, Groupes electrogenes, Moteurs et pompes`: "Énergie & Environnement",
		`Impression et amballage`: "Industrie & Fabrication",
		`Imprimerie`: "Industrie & Fabrication",
		`Imprimerie, imprimés et papiers, listings informatiques (blancs ou personnalisés)`: "Industrie & Fabrication",
		`Imprimeries`: "Industrie & Fabrication",
		`Imprimeries, Objets publicitaires`: "Industrie & Fabrication",
		`Industrie Minoterie`: "Industrie & Fabrication",
		`Industrie cosmétique`: "Industrie & Fabrication",
		`Industrie de Tabac`: "Industrie & Fabrication",
		`Industrie pharmaceutique`: "Industrie & Fabrication",
		`Information technology`: "Informatique & Télécoms",
		`Informatique`: "Services aux Entreprises (B2B)",
		`Informatique et Télécommunication`: "Informatique & Télécoms",
		`Informatique générale`: "Informatique & Télécoms",
		`Informatique, Création de site internet, Intégrateur de progiciels et logiciels de gestion, Marketing, Emailing, Archivage numérique, Formations professionnelles`: "Informatique & Télécoms",
		`Informatique, Création de site internet, Intégrateur de progiciels et logiciels de gestion, Marketing, Emailing, Archivage numérique, Formations professionnelles, Réseaux, Maintenance informatique, Audit, Conseil`: "Informatique & Télécoms",
		`Informatique, Photos et films, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Informatique, Télécommunication, Protection électrique`: "Informatique & Télécoms",
		`Informatique, consommables, hi-fi, video`: "Informatique & Télécoms",
		`Informatique, consultants, Informatique, formation, Informatique, maintenance, Informatique, reseaux`: "Informatique & Télécoms",
		`Informatique, formation`: "Informatique & Télécoms",
		`Informatique, logiciels, consommables`: "Informatique & Télécoms",
		`Informatique, maintenance`: "Informatique & Télécoms",
		`Informatique: Maintenance & support technique`: "Services aux Entreprises (B2B)",
		`Ingénierie Informatique`: "Informatique & Télécoms",
		`Ingénieurie et Management`: "Services aux Entreprises (B2B)",
		`Installateur en électricité`: "Services aux Entreprises (B2B)",
		`Installation porte automatique`: "Services aux Entreprises (B2B)",
		`Internet`: "Services aux Entreprises (B2B)",
		`Internet Solutions, Hébergement, Enregistrement, Webdesign`: "Hébergement & Tourisme",
		`Internet provider, Télécommunications, Informatique`: "Informatique & Télécoms",
		`Internet, Internet, provider, Telecommunications et telephonie`: "Informatique & Télécoms",
		`Internet, Internet, provider, Telecommunications, satellite, Telecommunications et telephonie`: "Informatique & Télécoms",
		`JURIDIQUE,FISCAL,AUDIT et COMPTABILITE`: "Services aux Entreprises (B2B)",
		`Journalisme`: "Services aux Entreprises (B2B)",
		`Juridiques et technologiques`: "Services aux Entreprises (B2B)",
		`Kinésithérapeute`: "Santé & Bien-être",
		`LE GENIE CIVIL, VENTE ET DISTRIBUTION DU CIMENT, LA FOURNITURE DU BUREAU ET DU MATERIEL INFORMATIQUE ET DIVERS`: "BTP & Construction",
		`La douane congolaise`: "Services aux Entreprises (B2B)",
		`Laboratoire indépendant d'analyses des produits miniers`: "Services aux Entreprises (B2B)",
		`Laboratoire médical, Santé`: "Santé & Bien-être",
		`Lait, yaourt et fromage, Laiteries, industries`: "Agriculture & Élevage",
		`Le spécialiste du transport routier`: "Automobile & Transports",
		`Les grands travaux de terrassement de l'industrie minière`: "BTP & Construction",
		`Lessive, savon, huile alimentaire`: "Restauration & Alimentation",
		`Librairie revues livres`: "Commerce & Distribution",
		`Librairie, Livres, Revues`: "Commerce & Distribution",
		`Librairies, papeteries, maisons de la presse`: "Culture, Sport & Loisirs",
		`Livraison des plis : colis, factures, invitations, courriers`: "Logistique & Entreposage",
		`Location d'appartement et studio, hôtel`: "Hébergement & Tourisme",
		`Location d'appartements`: "Hébergement & Tourisme",
		`Location de voitures`: "Automobile & Transports",
		`Location de voitures, Tourisme`: "Automobile & Transports",
		`Location et Vente de vehicule`: "Automobile & Transports",
		`Logiciel (Sofware)`: "Informatique & Télécoms",
		`Loisirs`: "Services aux Entreprises (B2B)",
		`Loisirs, Restaurants et bars`: "Restauration & Alimentation",
		`MEDIA ET TELECOM`: "Informatique & Télécoms",
		`MOTO DE TOURISME ET BICYCLETTE DE LOISIR`: "Automobile & Transports",
		`Machinery`: "Industrie & Fabrication",
		`Maintenance sur les produits Informatiques et bureautiques : PC, Portables, Serveurs, Imprimantes, Photocopieuses, Logiciels et accessoires`: "Informatique & Télécoms",
		`Mairies, Bourgmestres`: "Culture, Sport & Loisirs",
		`Maison de production`: "Culture, Sport & Loisirs",
		`Management,bureau d'etude et ingenierie conseil`: "Services aux Entreprises (B2B)",
		`Manutention et entreposage`: "Logistique & Entreposage",
		`Manutention et entreposage, Manutention portuaire, Transports routiers, Vehicules industriels`: "Automobile & Transports",
		`Marketing`: "Services aux Entreprises (B2B)",
		`Marketing et Communications`: "Services aux Entreprises (B2B)",
		`Marketing télévision, communications`: "Culture, Sport & Loisirs",
		`Marketing, Publicité, Hébergement`: "Hébergement & Tourisme",
		`Matelas, Menuiseries bois`: "Industrie & Fabrication",
		`Matériaux de construction`: "BTP & Construction",
		`Matériaux de construction, outillage`: "BTP & Construction",
		`Matériel ferroviaire - Exploitation de carrières`: "Services aux Entreprises (B2B)",
		`Matériel industriels`: "Services aux Entreprises (B2B)",
		`Medical, materiels`: "Santé & Bien-être",
		`Medical, materiels, Medical, produits, Pharmaceutiques, industries, Pharmaceutiques, produits`: "Santé & Bien-être",
		`Menuiseries bois`: "Services aux Entreprises (B2B)",
		`Mercedes-Benz et importateur Mitsubishi Motors Corporation`: "Services aux Entreprises (B2B)",
		`Mines`: "Services aux Entreprises (B2B)",
		`Mines et transformation du Cu en lingots`: "Mines & Extraction",
		`Mines, exploitation`: "Mines & Extraction",
		`Mines, laboratoires d'analyses`: "Mines & Extraction",
		`Ministère`: "Culture, Sport & Loisirs",
		`Ministère de l'éducation`: "Enseignement & Formation",
		`Ministère de la santé`: "Culture, Sport & Loisirs",
		`Ministère des Mines, Administration de l'Industrie`: "Mines & Extraction",
		`Mobilier , électroménager`: "Services aux Entreprises (B2B)",
		`Money Transfer App`: "Informatique & Télécoms",
		`Monrespro`: "Services aux Entreprises (B2B)",
		`Motorcycles`: "Automobile & Transports",
		`Mouture de maïs en grain et ensachage de la farine.`: "Agriculture & Élevage",
		`Mèches capillaires et produits de beauté`: "Services aux Particuliers (B2C)",
		`Mécanique automobile toutes marques`: "Automobile & Transports",
		`Métallurgie, sidérurgie et activités associées`: "Services aux Entreprises (B2B)",
		`NEGOCE & TRADING`: "Commerce & Distribution",
		`Night club, club de nuit, bar`: "Culture, Sport & Loisirs",
		`Night clubs et discotheques, Restaurants et bars`: "Restauration & Alimentation",
		`O.n.g et organisations internationales`: "Culture, Sport & Loisirs",
		`ONG`: "Services aux Entreprises (B2B)",
		`ONG de recherche action et d'appui au développement communautaire au profit de la jeunesse et du genre`: "Services aux Entreprises (B2B)",
		`OPTICIEN LUNETIER`: "Services aux Entreprises (B2B)",
		`Onduleurs (UPS) MGE UBS SYSTEMS : Distributeur officiel vente et`: "Services aux Entreprises (B2B)",
		`Opticiens`: "Services aux Entreprises (B2B)",
		`Opérateur télécom - GSM - Mobile`: "Informatique & Télécoms",
		`Organisation, Fond Social de la RDC`: "Services aux Entreprises (B2B)",
		`Organisations internationales`: "Culture, Sport & Loisirs",
		`Organisme de lutte contre le Sida`: "Santé & Bien-être",
		`Organisme de santé, Lutte contre le SIDA`: "Santé & Bien-être",
		`Organisme gouvernemental`: "Services aux Entreprises (B2B)",
		`Organismes internationaux`: "Culture, Sport & Loisirs",
		`PEINTURE AUTO`: "Services aux Entreprises (B2B)",
		`PRINTING SHOP`: "Services aux Entreprises (B2B)",
		`PRODUCTION ET RÉALISATION CINÉMATOGRAPHIQUE`: "Culture, Sport & Loisirs",
		`Packaging Manufacturer, Custom Full-Color Printing`: "Industrie & Fabrication",
		`Papiers, cartons, cahiers`: "Services aux Entreprises (B2B)",
		`Peintres en batiments et travaux publics, Peinture`: "BTP & Construction",
		`Peinture`: "Services aux Entreprises (B2B)",
		`Pharmaceutiques, distributeurs`: "Santé & Bien-être",
		`Pharmaceutiques, distributeurs, Pharmaceutiques, produits`: "Santé & Bien-être",
		`Pharmaceutiques, industries, Pharmaceutiques, produits`: "Santé & Bien-être",
		`Pharmaceutiques, produits`: "Santé & Bien-être",
		`Pharmacie`: "Services aux Entreprises (B2B)",
		`Pharmacies`: "Services aux Entreprises (B2B)",
		`Pharmacies, Pharmaciens`: "Santé & Bien-être",
		`Piscines`: "Services aux Entreprises (B2B)",
		`Pièces de Rechanges ; Les meilleures en Filtres pour touts engins, véhicules, pnéumatiques etc; Informatique (Bureautique & Cyber), Magasin des Filtres; Patisserie...`: "Services aux Entreprises (B2B)",
		`Pièces de rechange auto et camions toutes marques`: "Services aux Entreprises (B2B)",
		`Plastic Injection Molding Robot`: "Industrie & Fabrication",
		`Plastique`: "Services aux Entreprises (B2B)",
		`Plastique, industries, Plastique, produits`: "Industrie & Fabrication",
		`Plateforme d'échange`: "Services aux Entreprises (B2B)",
		`Pompes funèbres, funéraires, funérailles, inhumations, crémations, funérariums`: "Services aux Particuliers (B2C)",
		`Portail des affaires`: "Culture, Sport & Loisirs",
		`Ports`: "Services aux Entreprises (B2B)",
		`Presse audiovisuelle`: "Culture, Sport & Loisirs",
		`Presse, Journal`: "Culture, Sport & Loisirs",
		`Production d'eau minérale en bouteilles PET`: "Énergie & Environnement",
		`Production de ciment Portland`: "Industrie & Fabrication",
		`Production et Distribution d'Électricité`: "Énergie & Environnement",
		`Production et distribution de boissons alcoolisées et sucrées`: "Industrie & Fabrication",
		`Production industrielle de chaussures en cuir et polymère`: "Industrie & Fabrication",
		`Produits PANDORA, bonbons BUTTER SCOTCH, produits de beauté VITA`: "Services aux Particuliers (B2C)",
		`Produits chimiques, plastiques et dérivés`: "Services aux Entreprises (B2B)",
		`Produits industriels, électroménager, climatiseurs, consommables`: "Services aux Entreprises (B2B)",
		`Programmation`: "Informatique & Télécoms",
		`Programme des Jeunes pour un Leadership Dynamique`: "Culture, Sport & Loisirs",
		`Projet de retraitement des rejets`: "Services aux Entreprises (B2B)",
		`Projets d'électrification et d'éclairage public`: "Énergie & Environnement",
		`Projets et bureaux d'appui`: "Services aux Entreprises (B2B)",
		`Prêt d'argent`: "Services aux Entreprises (B2B)",
		`Publicité, média, information, communication`: "Services aux Entreprises (B2B)",
		`Pétrol, lubrifiant, gazoil, pour véhicule aérien et terrestre`: "Énergie & Environnement",
		`Quincaillerie générale, outillages, accessoires`: "Commerce & Distribution",
		`REGIE DE DISTRIBUTION D'EAU  DE LA  REPUBLIQUE DEMOCRATIQUE DU CONGO`: "Services aux Entreprises (B2B)",
		`Radio et Télévision sur Intenet`: "Services aux Entreprises (B2B)",
		`Radio et television`: "Culture, Sport & Loisirs",
		`Radio, Télévision, Télédistribution, Internet`: "Culture, Sport & Loisirs",
		`Recherche`: "Services aux Entreprises (B2B)",
		`Relations publiques et organisations de manifestations, Tourisme`: "Services aux Entreprises (B2B)",
		`Représentant exclusif des lubrifiants CHAMPION.`: "Services aux Entreprises (B2B)",
		`Représentant officiel en R.D.C. des marques KIA et DAIHATSU`: "Services aux Entreprises (B2B)",
		`Représentation officielle de FUJIFILM`: "Services aux Entreprises (B2B)",
		`Ressources utiles pour vos préparations aux différents examens.`: "Enseignement & Formation",
		`Restaurant`: "Services aux Entreprises (B2B)",
		`Restaurants`: "Services aux Entreprises (B2B)",
		`Restaurants et bars`: "Restauration & Alimentation",
		`Restaurants et bars, Traiteurs`: "Restauration & Alimentation",
		`Réfrigérateurs, Froid, Air conditionnée, Cuisinières, Lessiveuses, Vente et installation de système de climatisation`: "Services aux Entreprises (B2B)",
		`Réfrigération, La Climatisation, Conditionnement d'air, La Plomberie, Réseau adduction, RIA et Désenfumage`: "Services aux Entreprises (B2B)",
		`Référencement d'entreprises et particuliers`: "Services aux Entreprises (B2B)",
		`Réparation automobile, entretien, mécanique, carrosserie, suspension, tolerie, peinture`: "Automobile & Transports",
		`Réseau Social LIBOTA`: "Culture, Sport & Loisirs",
		`Réseau de distribution, agro-alimentaire, mèches`: "Agriculture & Élevage",
		`Réservation hôtels en ligne`: "Hébergement & Tourisme",
		`S'exprimer par l'expression du savoir`: "Services aux Entreprises (B2B)",
		`SCIAGE ET COMMERCE DE BOIS`: "Services aux Entreprises (B2B)",
		`SECURITE DES BIENS ET DES PERSONNES`: "Services aux Entreprises (B2B)",
		`SPOTS PUBLICITAIRES, CLIP MUSICAUX, DOCUMENTAIRES, DOCUMENTAIRES, EMMISSION TELEVISEE, TELEREALITE`: "Services aux Entreprises (B2B)",
		`STREAMING TV AND RADIO OVER INTERNET`: "Informatique & Télécoms",
		`Safari Club International`: "Hébergement & Tourisme",
		`Sales Outsourcing et Marketing Digital`: "Informatique & Télécoms",
		`Santé, Organisation,`: "Santé & Bien-être",
		`Sapeurs pompiers`: "Culture, Sport & Loisirs",
		`Secrétariat Général de la Comptabilité`: "Services aux Entreprises (B2B)",
		`Secteur Académique, Institut supérieur`: "Enseignement & Formation",
		`Security Protection & Investigations`: "Services aux Entreprises (B2B)",
		`Serrure biométrique, Serrure à empreintes digitales, Sécurités des systèmes informatiques`: "Informatique & Télécoms",
		`Service Batiment et Tout corps d'etat`: "BTP & Construction",
		`Service provider de VODACOM - THURAYA`: "Services aux Entreprises (B2B)",
		`Service public - Service des douanes - Direction Générale`: "Services aux Entreprises (B2B)",
		`Service public - Service des impôts - Administration Centrale`: "Services aux Entreprises (B2B)",
		`Service public - Service des recettes non fiscales - Administration Centrale`: "Services aux Entreprises (B2B)",
		`Service, Gestion du Personnel`: "Services aux Entreprises (B2B)",
		`Services Informatique`: "Informatique & Télécoms",
		`Services d'urgence et d'assistance, police`: "Services aux Entreprises (B2B)",
		`Services de livraison en ligne`: "Logistique & Entreposage",
		`Services et conseil aux entreprises`: "Services aux Entreprises (B2B)",
		`Services informatiques et de conseils en solutions digitales`: "Informatique & Télécoms",
		`Shot Blasting Machine`: "Industrie & Fabrication",
		`Site Web / Apprentissage en électronique`: "Informatique & Télécoms",
		`Site web`: "Informatique & Télécoms",
		`Société de Service en Ingénierie Informatique`: "Informatique & Télécoms",
		`Société de service spécialisée dans l'informatique`: "Services aux Entreprises (B2B)",
		`Soins, beauté et bien être`: "Santé & Bien-être",
		`Solutions informatiques pour entreprise`: "Informatique & Télécoms",
		`Spécialiste en textile et ameublement : tissus toutes qualités`: "Services aux Entreprises (B2B)",
		`Spécialités Mèches DARLING et plantes pour cheveux - PONY TAIL`: "Services aux Entreprises (B2B)",
		`Stations de radio sur FM et Internet`: "Culture, Sport & Loisirs",
		`Stone Manufacturer`: "Industrie & Fabrication",
		`Studio de création audiovisuelle`: "Culture, Sport & Loisirs",
		`Sucre, fabrication et raffinage`: "Mines & Extraction",
		`Supermarches`: "Services aux Entreprises (B2B)",
		`Supermarchés, Magasins, Centre commerciale`: "Services aux Entreprises (B2B)",
		`Suppliers of Chemicals, Fournisseurs de produits chimiques`: "Services aux Entreprises (B2B)",
		`Systèmes de connexion à Internet`: "Informatique & Télécoms",
		`Sécurite et protection incendie en afrique`: "Services aux Entreprises (B2B)",
		`Sécurité et Gardiennage`: "Services aux Entreprises (B2B)",
		`TECH HUB, COWORKING, INCUBATEUR, LAB D'INNOVATION`: "Services aux Entreprises (B2B)",
		`TOURNAGE MECANIQUE ,INDUSTRIES`: "Services aux Entreprises (B2B)",
		`TRANSPORT FLUVIAL`: "Culture, Sport & Loisirs",
		`TRANSPORT FRIGORIFIQUE, IMPORT-EXPORT`: "Culture, Sport & Loisirs",
		`Technologie Financière  (Fintech )`: "Informatique & Télécoms",
		`Telechargements de la musique kasaiene`: "Culture, Sport & Loisirs",
		`Telecommunications et telephonie`: "Informatique & Télécoms",
		`Telecommunications, mobiles`: "Informatique & Télécoms",
		`Telecommunications, satellite`: "Informatique & Télécoms",
		`Textile`: "Services aux Entreprises (B2B)",
		`Textile, PAGNES - African printing`: "Commerce & Distribution",
		`The, production et commercialisation`: "Agriculture & Élevage",
		`Topper Smart Bidet Tiolet Seat Co., Ltd.`: "Services aux Entreprises (B2B)",
		`Tourisme`: "Services aux Entreprises (B2B)",
		`Tout matériaux de construction`: "BTP & Construction",
		`Tractor Supply Company`: "Industrie & Fabrication",
		`Traducteurs et interpretes`: "Services aux Entreprises (B2B)",
		`Traduction et interprétation`: "Services aux Entreprises (B2B)",
		`Traduction/Interpretariat`: "Services aux Entreprises (B2B)",
		`Traitement industriel du coton graine en coton fibre`: "Agriculture & Élevage",
		`Transformation des matières plastiques`: "Industrie & Fabrication",
		`Transformation des matières plastiques par injection`: "Industrie & Fabrication",
		`Transformation du lait`: "Industrie & Fabrication",
		`Transit et consignation`: "Logistique & Entreposage",
		`Transit maritime`: "Logistique & Entreposage",
		`Transitaires et Agence en Douane`: "Logistique & Entreposage",
		`Transport`: "Culture, Sport & Loisirs",
		`Transport Multimodal`: "Logistique & Entreposage",
		`Transport Routier`: "Automobile & Transports",
		`Transport aérien`: "Culture, Sport & Loisirs",
		`Transport aérien, maritime, routier, fluvial et ferroviaire`: "Automobile & Transports",
		`Transport aérien, maritime. Importation. Exportation`: "Automobile & Transports",
		`Transport aérien, réservation de billets, voyage`: "Automobile & Transports",
		`Transport de bagages`: "Logistique & Entreposage",
		`Transport fluvial`: "Culture, Sport & Loisirs",
		`Transport fluvial, lacustre et routier`: "Automobile & Transports",
		`Transport frigorifique - Conventionnel - Exceptionnel - Containe`: "Culture, Sport & Loisirs",
		`Transport routier international`: "Automobile & Transports",
		`Transport voyage par bus`: "Automobile & Transports",
		`Transport, logistique, voyage et tourisme, import et export, aviation, commerce general`: "Logistique & Entreposage",
		`Transporteur routier officiel en RDC`: "Culture, Sport & Loisirs",
		`Transports Transitaire et Agent Maritime`: "Culture, Sport & Loisirs",
		`Transports aeriens, Transports maritimes`: "Automobile & Transports",
		`Transports aériens`: "Culture, Sport & Loisirs",
		`Transports aériens, Compagnies aeriennes`: "Automobile & Transports",
		`Transports fluviaux`: "Automobile & Transports",
		`Transports routiers`: "Automobile & Transports",
		`Transports routiers en tous genres`: "Automobile & Transports",
		`Travail temporaire, interim`: "Services aux Entreprises (B2B)",
		`Travaux - Contruction - Réfection`: "BTP & Construction",
		`Travaux d'Assainissement`: "BTP & Construction",
		`Travaux de terrassement, réhabilitation de routes en terre.`: "BTP & Construction",
		`Travaux publics : bétonnage, drainage, construction`: "BTP & Construction",
		`Travaux publics, Construction, Plomberie, Maçonnerie, Froid et climatisation, Peinture`: "BTP & Construction",
		`Travaux routiers et génie civil`: "BTP & Construction",
		`Télécommunication GSM`: "Informatique & Télécoms",
		`Télécommunication, Opérateur GSM`: "Informatique & Télécoms",
		`Télécommunication, Téléphonie`: "Informatique & Télécoms",
		`Télévisions, radios, électroménagers`: "Services aux Entreprises (B2B)",
		`Université`: "Services aux Entreprises (B2B)",
		`Université, académie`: "Enseignement & Formation",
		`Université, École`: "Enseignement & Formation",
		`Usine de fabrication de pain, Boulangerie`: "Industrie & Fabrication",
		`Vehicules industriels`: "Automobile & Transports",
		`Vente d'ordinateurs et materiel informatique`: "Informatique & Télécoms",
		`Vente de boissons alcoolisées de marque internationale (whisky, vin, liqueur,...) et de production sud-africaine`: "Restauration & Alimentation",
		`Vente de camions d'occasion`: "Automobile & Transports",
		`Vente de matériaux de construction`: "BTP & Construction",
		`Vente de matériel audiovisuel`: "Culture, Sport & Loisirs",
		`Vente de matériel informatique, installation de réseaux`: "Informatique & Télécoms",
		`Vente de médicaments`: "Santé & Bien-être",
		`Vente de petits et gros électro-ménager, air conditionnée, climatisation, téléviseur,`: "Services aux Entreprises (B2B)",
		`Vente de pneus agricoles`: "Agriculture & Élevage",
		`Vente de téléphones cellulaires et accessoires`: "Informatique & Télécoms",
		`Vente de véhicules neufs TOYOTA et SUZUKI`: "Services aux Entreprises (B2B)",
		`Vente des Services en linge`: "Services aux Entreprises (B2B)",
		`Vente en ligne des produits de consommation`: "Restauration & Alimentation",
		`Vente et Conseil des produits pharmaceutiques`: "Santé & Bien-être",
		`Vente et distribution de produits pour l'agriculture moderne`: "Services aux Entreprises (B2B)",
		`Vente et location des biens immobiliers`: "Immobilier",
		`Vente pièces de rechange`: "Services aux Entreprises (B2B)",
		`Vente pièces de rechange automobile d'origine`: "Services aux Entreprises (B2B)",
		`Vente produits et service electrique`: "Services aux Entreprises (B2B)",
		`Vente, entretien et réparation des véhicules IVECO`: "Automobile & Transports",
		`Vente, installation et maintenance de matériel électrique pour gros et petit ouvrage. Représentant ABB`: "Services aux Entreprises (B2B)",
		`Ventes & achats des pièces rechanges`: "Services aux Entreprises (B2B)",
		`Ventes des cellulaires`: "Services aux Entreprises (B2B)",
		`Ventes des matériels informatique et divers`: "Services aux Entreprises (B2B)",
		`Verres correcteurs de stock : minéral blanc, organique anti-reflets, anti-griffres et photochromiques, opticien`: "Services aux Particuliers (B2C)",
		`Vidéo surveillance, contrôle d'accès, parlophones`: "Services aux Entreprises (B2B)",
		`Vulcanisation, montage et réparation des pneus, Vente des filtres et batteries`: "Automobile & Transports",
		`Webdesign`: "Informatique & Télécoms",
		`agricole,elevage,formation,vulgarisation`: "Agriculture & Élevage",
		`agricoles-maraichères-élèvage`: "Agriculture & Élevage",
		`alimentation générale`: "Services aux Entreprises (B2B)",
		`annonce`: "Culture, Sport & Loisirs",
		`annonces classées, Publicité`: "Culture, Sport & Loisirs",
		`articles de ménage et de cuisine, bazars`: "Services aux Entreprises (B2B)",
		`associations diverses, amicales, fondation`: "Culture, Sport & Loisirs",
		`associations humanitaires, d'entraide, d'action sociale`: "Culture, Sport & Loisirs",
		`associations, organismes culturels et socio-éducatifs`: "Culture, Sport & Loisirs",
		`bakery equipment`: "Industrie & Fabrication",
		`banques`: "Services aux Entreprises (B2B)",
		`bibliothèques, médiathèques`: "Services aux Entreprises (B2B)",
		`bijouterie, joaillerie`: "Services aux Particuliers (B2C)",
		`bureaux de change`: "Banque & Assurance",
		`cabinet Architecture`: "Services aux Entreprises (B2B)",
		`centres d'archives et de documentation`: "Services aux Entreprises (B2B)",
		`cliniques médicales`: "Santé & Bien-être",
		`commerce`: "Services aux Entreprises (B2B)",
		`commerce general`: "Commerce & Distribution",
		`communautés religieuses`: "Culture, Sport & Loisirs",
		`creation des sites web , apk et autres..`: "Informatique & Télécoms",
		`des systèmes de sécurité électronique,  d'identification et de communication  sans fil`: "Informatique & Télécoms",
		`distributeur exclusif des véhicules PEUGEOT et RENAULT TRUCKS`: "Services aux Entreprises (B2B)",
		`edition-presse`: "Culture, Sport & Loisirs",
		`fourniture fûts métalliques de 216 litres pour hydrocarbures`: "Énergie & Environnement",
		`furniture store`: "Commerce & Distribution",
		`import-export`: "Services aux Entreprises (B2B)",
		`importe et distribue à Kinshasa toutes pièces d'origine`: "Services aux Entreprises (B2B)",
		`informaticien`: "Informatique & Télécoms",
		`informatique`: "Services aux Entreprises (B2B)",
		`informatique,Eléctronique`: "Informatique & Télécoms",
		`location d'automobiles: tourisme et utilitaires`: "Services aux Entreprises (B2B)",
		`lock`: "Services aux Entreprises (B2B)",
		`magazine de communication`: "Services aux Entreprises (B2B)",
		`offres d'emploi`: "Services aux Entreprises (B2B)",
		`optical & medical supplies, opticien`: "Santé & Bien-être",
		`parti politique`: "Culture, Sport & Loisirs",
		`pharmacies`: "Services aux Entreprises (B2B)",
		`photo`: "Services aux Entreprises (B2B)",
		`production et vente des oeufs`: "Agriculture & Élevage",
		`programmation informatique pour débutant niveau zéro`: "Informatique & Télécoms",
		`quincaillerie`: "Commerce & Distribution",
		`restaurants`: "Services aux Entreprises (B2B)",
		`sanitary napkin making machine`: "Industrie & Fabrication",
		`solution informatique`: "Informatique & Télécoms",
		`surgelés: produits alimentaires, legumes frais`: "Services aux Entreprises (B2B)",
		`sécurisation des documents, carte d'identité, passeport, chèques`: "Services aux Entreprises (B2B)",
		`telecommunication`: "Informatique & Télécoms",
		`transfusion sanguine`: "Santé & Bien-être",
		`transport en messagerie express, coursiers internationaux`: "Logistique & Entreposage",
		`transport et logistique`: "Culture, Sport & Loisirs",
		`transports aériens`: "Culture, Sport & Loisirs",
		`truck`: "Services aux Entreprises (B2B)",
		`téléphonie mobile, radiomessagerie, radiocommunications`: "Services aux Entreprises (B2B)",
		`une entreprise générale du bâtiment tous corps d'état (TCE)`: "BTP & Construction",
		`une entréprise en informatique`: "Informatique & Télécoms",
		`Échange de cryptomonnaies`: "Banque & Assurance",
		`École, Groupe Scolaire`: "Enseignement & Formation",
		`Écoles et universites`: "Enseignement & Formation",
		`Électricité`: "Services aux Entreprises (B2B)",
		`Électricité, sécurité électronique, construction, marketing digital`: "BTP & Construction",
		`Électroménager`: "Services aux Entreprises (B2B)",
		`Électronique et Électroménager, Meubles et Bureaux, Décoration d'intérieur et Luminaires, Linges de maison, rideaux et tapis`: "Services aux Entreprises (B2B)",
		`Éxploitations minières`: "Services aux Entreprises (B2B)",
		`églises chrétiennes diverses, communautés religieuses`: "Culture, Sport & Loisirs",
		`établissements financiers, finances`: "Banque & Assurance",
		`établissements financiers, transfert d'argent`: "Banque & Assurance",
}

// =============================================================================
// Keyword fallback  (substring, case-insensitive)
// =============================================================================

var activityKeywords = []struct {
	canonical string
	keywords  []string
}{
	{ActAgricultureElevage, []string{
		"agricol", "élevage", "elevage", "cacao", "huileri", "laiterie",
		"abattoir", "maraich", "phytosanit", "piscicult", "bovin", "ovin", "porcin",
		"mouture", "plantation", "semence", "agro-alim", "agro-ind", "agro-industrie",
		"agro-alimentaire", "agriculture,", "coton,",
	}},
	{ActMinesExtraction, []string{
		"mines, exploitation", "activité minière", "activite miniere",
		"diamant", "cobalt", "carrieres, exploitation", "raffinage",
		"exploitations minières", "exportation de minerais", "minerais",
		"exploitation de diamants", "mines, recherche", "mines\n", "mines,",
	}},
	{ActIndustrieFabrication, []string{
		"fabrication de", "manufactur", "plastique, industries", "caoutchouc, industries",
		"emballage et conditionnement", "imprimeries", "imprimerie", "papier, industries",
		"cartonnerie", "sucre, fabrication", "chaussures, manufactures", "allumettes",
		"transformation des matières", "scieries", "aluminium, industries",
		"briqueteries", "chimie, industries", "fer et acier", "constructions metalliques",
		"minoterie", "transformation du lait", "transformation du coton", "serigraphie",
	}},
	{ActEnergieEnvironnement, []string{
		"énergie solaire", "energie solaire", "groupe electrogene", "groupes electrogenes",
		"electricite generale", "electricite, materiels", "assainissement et canal",
		"eau, traitement", "eau de source", "adduction d'eau",
		"hydrocarbures, distribution", "hydrocarbures, lubrifiants", "hydrocarbures, stockage",
		"bitume, fabrication", "pétroliers", "environnement,",
		"projets d'électrification", "distribution de carburants",
	}},
	{ActBTPConstruction, []string{
		"batiments et travaux publics", "génie civil", "genie civil",
		"travaux publics", "terrassement", "plomberie et sanitaires",
		"architecture et urbanisme", "bureaux d'etudes et d'ingenierie",
		"etancheite,", "beton, fabrication", "entreprises de bâtiment",
		"construction générale", "construction immobilière",
		"tous corps d'état", "travaux de terrassement", "travaux routiers",
		"travaux d'assainissement", "matériaux de construction",
		"btp\n", "btp,", "bâtiment\n", "bâtiment,", "architecte",
	}},
	{ActAutomobileTransports, []string{
		"automobiles et concessionnaires", "automobiles, pieces", "vehicules industriels",
		"transports aeriens", "compagnie aérienne", "compagnies aeriennes",
		"transport routier", "transports routiers", "transports fluviaux",
		"transport maritime", "transports maritimes", "transport ferroviaire",
		"aéroports", "aeroports", "location de voitures", "vulcanisation",
		"garages,", "garages\n", "cycles et motos",
		"concessionnaire automobile", "importateur et concessionnaire",
		"mécanique automobile", "mecanique automobile", "réparation automobile",
	}},
	{ActLogistiqueEntreposage, []string{
		"manutention et entreposage", "manutention portuaire", "transit et consignation",
		"agences en douane", "fret\n", "fret,", "fret aérien", "fret maritime",
		"courriers express", "livraison", "demenagements", "déménagements",
		"transit maritime", "agence maritime", "agences maritimes", "transitaires",
		"logistique,", "logistique\n", "transport multimodal", "avitaillement maritime",
		"administration, gestion du fret",
	}},
	{ActHebergementTourisme, []string{
		"hôtel,", "hotel,", "hotels,", "hôtels", "hébergement",
		"tourisme,", "tourisme\n", "flat, motel", "agence de voyage",
		"agences de voyages", "maison d'hôte", "safari", "location d'appartement",
		"hôtellerie", "hotellerie",
	}},
	{ActRestaurationAlimentation, []string{
		"restaurants et bars", "restaurant\n", "restaurants\n",
		"traiteurs,", "catering,", "boulangeries et patisseries", "boulangerie,",
		"alimentation generale", "supermarches", "supermarchés", "fast food",
		"boissons,", "boissons\n", "alimentaire, produits", "salons de the",
		"restauration\n", "restauration,",
	}},
	{ActInformatiqueTelocoms, []string{
		"informatique,", "informatique\n", "telecom", "télécommunication",
		"internet,", "internet\n", "logiciel", "software", "webdesign",
		"site web", "e-commerce", "numérique", "digital", "bureautique,", "bureautique\n",
		"développement informatique", "maintenance informatique",
		"intelligence artificielle", "automatisation", "programmation",
		"ingénierie informatique", "solutions informatiques", "information technology",
		"geolocalisation", "biometrie", "data management", "technologie financière",
		"fintech", "media et telecom", "opérateur télécom", "télécommunication gsm",
	}},
	{ActBanqueAssurance, []string{
		"banque,", "banques,", "banques\n", "banque\n",
		"assurances,", "assurances\n", "assureurs", "finances,", "finances\n",
		"crédit", "transfert de fonds", "transfert d'argent",
		"bureaux de change", "établissements financiers", "etablissements financiers",
		"banques et organismes financiers", "échange de cryptomonnaies",
	}},
	{ActImmobilier, []string{
		"immobilier,", "immobilier\n", "agence immobilière", "agence immobiliere",
		"agences immobilières", "agences immobilieres",
		"gestion immobilière", "expertise immobilière", "immobilier, agences",
	}},
	{ActSanteBienEtre, []string{
		"santé,", "santé\n", "cliniques et hopitaux", "clinique,", "cabinets medicaux",
		"pharmacies,", "pharmacies\n", "pharmaceutiques, distributeurs",
		"pharmaceutiques, industries", "pharmaceutiques, produits",
		"medical, materiels", "laboratoire médical", "kinésithérapeute",
		"lutte contre le sida", "sida", "transfusion sanguine",
		"hôpital,", "pharmacie\n", "pharmacie,",
	}},
	{ActEnseignementFormation, []string{
		"ecoles et universites", "écoles et universites", "université,", "universite,",
		"université\n", "ecole,", "école,", "formation professionnelle",
		"centres de formation", "centre de formation", "enseignement",
		"académie", "academie", "formation universitaire", "humanités",
		"ecole conventionnee", "formation et sensibilisation",
	}},
	{ActCultureSportLoisirs, []string{
		"loisirs,", "loisirs\n", "loisir,", "musique", "cinemas", "audiovisuel",
		"galerie d'art", "galerie d'exposition", "presse", "night club", "discotheque",
		"casino", "églises", "eglise", "associations diverses", "associations humanitaires",
		"ong\n", "organisations internationales", "festival", "associations, organismes",
		"édition", "edition-presse", "agences de presse",
		"maison de production", "studio de création audiovisuelle",
		"stations de radio", "ambassade", "consulat", "parti politique",
		"ministère", "mairies", "fonds des nations", "sapeurs pompiers",
		"communautés religieuses", "o.n.g", "féderation congolaise",
	}},
	{ActServicesB2C, []string{
		"coiffeurs", "beauté,", "beaute,", "opticiens,", "opticien\n",
		"blanchisseries", "pompes funèbres", "bijouterie, joaillerie",
		"mèches capillaires", "cosmetiques, produits", "verres correcteurs",
		"agence de mannequin", "soins, beauté",
	}},
	{ActCommerceDistribution, []string{
		"commerce general", "commerce\n", "commerce,", "distribution,",
		"négoce", "negoce", "trading", "boutiques,", "quincaillerie",
		"agencement et decoration", "fournitures de bureaux", "librairies",
		"ameublement et mobilier", "textile\n", "textile,",
	}},
}

// =============================================================================
// ActivityNormalizeStep
// =============================================================================

type ActivityNormalizeStep struct{}

func (s *ActivityNormalizeStep) Name() string { return "Activity Normalizer" }

func (s *ActivityNormalizeStep) Process(_ context.Context, records []map[string]interface{}) ([]map[string]interface{}, error) {
	for _, record := range records {
		s.normalize(record)
	}
	return records, nil
}

func (s *ActivityNormalizeStep) normalize(record map[string]interface{}) {
	raw, ok := record["activity"].(string)
	if !ok {
		return
	}

	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return
	}

	// Fast path: exact static map lookup.
	if canonical, found := activityMapping[trimmed]; found {
		if trimmed != canonical {
			log.Debug().Msgf("[activity_normalizer] %q → %q (exact)", trimmed, canonical)
		}
		record["activity"] = canonical
		return
	}

	// Slow path: keyword substring scan (catches new / variant values).
	lower := strings.ToLower(trimmed)
	for _, entry := range activityKeywords {
		for _, kw := range entry.keywords {
			if strings.Contains(lower, kw) {
				log.Debug().Msgf("[activity_normalizer] %q → %q (keyword: %q)", trimmed, entry.canonical, kw)
				record["activity"] = entry.canonical
				return
			}
		}
	}

	// Fallback.
	log.Warn().Msgf("[activity_normalizer] unrecognized activity %q → %q (fallback)", trimmed, ActServicesB2B)
	record["activity"] = ActServicesB2B
}