---
http:
  services:
    congopro-bridge-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8110"

  middlewares:
    congopro-bridge-header-mdw:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  routers:
    congopro-bridge-router:
      rule: "Host(`congopro.com`) || Host(`www.congopro.com`)"
      service: congopro-bridge-service
      entryPoints: [websecure]
      # middlewares:
      #   - congopro-bridge-header-mdw
      tls:
        certResolver: letsencrypt
