// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "congopro-bridge/internal/ads"

// AdsPreviewPage is the advertiser-facing format reference at /ads-preview.
// It renders the REAL ad components (adSlot / premiumHomepageAd) with sample
// data rather than a client-side copy of them — the previous version carried
// its own JS reimplementation, which had already drifted from what the site
// actually serves. Same components here means the preview cannot lie.
func AdsPreviewPage(canonicalURL, nonce, cssVersion string, previews []ads.AdWire) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = siteHeader().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <main class=\"w-full max-w-4xl mx-auto px-4 sm:px-6 pt-10 pb-24\"><div class=\"text-center\"><h1 class=\"font-sora font-semibold text-3xl sm:text-4xl text-ink tracking-tight\">Formats publicitaires</h1><p class=\"mt-3 text-[15px] text-ink-muted max-w-xl mx-auto leading-relaxed\">Guide de référence : voici exactement comment votre annonce apparaîtra sur Congopro Bridge. Ces exemples utilisent les mêmes composants que le site en production.</p></div><section class=\"mt-12\"><h2 class=\"text-xs font-semibold uppercase tracking-[0.08em] text-ink-faint mb-4\">Emplacement : page d'accueil (premium)</h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(previews) > 0 {
				templ_7745c5c3_Err = premiumHomepageAd(previews[0], ValidateURL(previews[0].URL)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section><section class=\"mt-14\"><h2 class=\"text-xs font-semibold uppercase tracking-[0.08em] text-ink-faint mb-4\">Emplacement : résultats de recherche</h2><p class=\"text-sm text-ink-muted mb-5\">Un libellé par style disponible — le libellé et la couleur d'accent sont choisis à la création de la campagne.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, ad := range previews {
				templ_7745c5c3_Err = adSlot(ad).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section><section class=\"mt-14 rounded-2xl border border-line bg-surface-raised shadow-card p-5\"><h2 class=\"font-sora font-semibold text-[15px] text-ink mb-2\">Vous souhaitez annoncer ?</h2><p class=\"text-sm text-ink-muted leading-relaxed\">Écrivez-nous depuis la page <a href=\"/help\" preload=\"mousedown\" class=\"text-accent hover:underline\">Aide</a> ou passez par votre <a href=\"/account\" preload=\"mousedown\" class=\"text-accent hover:underline\">Espace entreprise</a> pour mettre en avant votre fiche.</p></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Formats publicitaires | Congopro Bridge", canonicalURL, nonce, cssVersion).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
