// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"time"
)

// SiteFooter is the shared "© Congopro · Support · Aide · Confidentialité ·
// Conditions" bar used on every page — the SSR pages (via Layout) and the
// SPA (index.html, rendered separately by the Go handler and injected as
// pre-rendered HTML since index.html uses html/template, not templ).
// mt-auto/shrink-0 assume a `flex flex-col` ancestor (see Layout's <body> and
// index.html's <body>) — that's the "sticky footer" pattern: it sits at the
// bottom of the viewport when content is short, and flows naturally after
// content when there's more than a screenful, without a leftover scrollbar.
func SiteFooter() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"w-full text-xs text-gray-400 text-center px-4 py-6 mt-auto shrink-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(siteFooterHTML()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func siteFooterHTML() string {
	year := strconv.Itoa(time.Now().Year())
	link := func(href, label string) string {
		return `<a href="` + href + `" class="hover:text-gray-600 hover:underline transition-colors">` + label + `</a>`
	}
	return "© " + year + " Congopro · " +
		`<a href="https://t.me/+yzJqliLeudNkZjY0" target="_blank" rel="noopener noreferrer" class="hover:text-gray-600 hover:underline transition-colors">Support</a> · ` +
		link("/help", "Aide") + " · " +
		link("/privacy", "Confidentialité") + " · " +
		link("/terms", "Conditions")
}

var _ = templruntime.GeneratedTemplate
