// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"time"
)

// SiteFooter is the shared "© Congopro · Support · Aide · Confidentialité ·
// Conditions" bar used on every page — the SSR pages (via Layout) and the
// SPA (index.html, rendered separately by the Go handler and injected as
// pre-rendered HTML since index.html uses html/template, not templ).
// mt-auto/shrink-0 assume a `flex flex-col` ancestor (see Layout's <body> and
// index.html's <body>) — that's the "sticky footer" pattern: it sits at the
// bottom of the viewport when content is short, and flows naturally after
// content when there's more than a screenful, without a leftover scrollbar.
func SiteFooter(nonce string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"w-full text-xs text-ink-faint text-center px-4 py-6 mt-auto shrink-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(siteFooterHTML()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = themeToggle(nonce).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// themeToggle is the 3-state theme control (Auto/Clair/Sombre) shared by
// the public footer and the admin sidebar. Self-contained: markup plus a
// nonce'd script, so it works on pages that do not load app.js. Light is
// the default; « Auto » (follow the system) and « Sombre » are opt-in.
func themeToggle(nonce string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"mt-3 flex items-center justify-center gap-1\" role=\"group\" aria-label=\"Choix du thème\"><span class=\"mr-1\">Thème&nbsp;:</span> <button type=\"button\" data-set-theme=\"auto\" class=\"theme-toggle-btn px-2 py-1\" aria-pressed=\"false\">Auto</button> <span aria-hidden=\"true\">·</span> <button type=\"button\" data-set-theme=\"light\" class=\"theme-toggle-btn px-2 py-1\" aria-pressed=\"false\">Clair</button> <span aria-hidden=\"true\">·</span> <button type=\"button\" data-set-theme=\"dark\" class=\"theme-toggle-btn px-2 py-1\" aria-pressed=\"false\">Sombre</button></div><script nonce=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(nonce)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/footer.templ`, Line: 36, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">\n\t\t(function () {\n\t\t\tvar KEY = \"cp_theme\";\n\t\t\tfunction stored() {\n\t\t\t\ttry { return localStorage.getItem(KEY); } catch (e) { return null; }\n\t\t\t}\n\t\t\tfunction paint() {\n\t\t\t\tvar pref = stored();\n\t\t\t\tvar mode = pref === \"auto\" || pref === \"dark\" ? pref : \"light\";\n\t\t\t\tvar resolved = mode === \"auto\"\n\t\t\t\t\t? (matchMedia(\"(prefers-color-scheme: dark)\").matches ? \"dark\" : \"light\")\n\t\t\t\t\t: mode;\n\t\t\t\tdocument.documentElement.dataset.theme = resolved;\n\t\t\t\tdocument.querySelectorAll(\"[data-set-theme]\").forEach(function (b) {\n\t\t\t\t\tb.setAttribute(\"aria-pressed\", String(b.getAttribute(\"data-set-theme\") === mode));\n\t\t\t\t});\n\t\t\t\tvar m = document.querySelector('meta[name=\"theme-color\"]');\n\t\t\t\tif (m) m.setAttribute(\"content\", resolved === \"dark\" ? \"#171a21\" : \"#be0203\");\n\t\t\t}\n\t\t\tdocument.querySelectorAll(\"[data-set-theme]\").forEach(function (b) {\n\t\t\t\tb.addEventListener(\"click\", function () {\n\t\t\t\t\tvar v = b.getAttribute(\"data-set-theme\");\n\t\t\t\t\ttry {\n\t\t\t\t\t\tif (v === \"light\") localStorage.removeItem(KEY);\n\t\t\t\t\t\telse localStorage.setItem(KEY, v);\n\t\t\t\t\t} catch (e) {}\n\t\t\t\t\tpaint();\n\t\t\t\t});\n\t\t\t});\n\t\t\ttry {\n\t\t\t\tmatchMedia(\"(prefers-color-scheme: dark)\").addEventListener(\"change\", function () {\n\t\t\t\t\tif (stored() === \"auto\") paint();\n\t\t\t\t});\n\t\t\t} catch (e) {}\n\t\t\tpaint();\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func siteFooterHTML() string {
	year := strconv.Itoa(time.Now().Year())
	link := func(href, label string) string {
		return `<a href="` + href + `" preload="mousedown" class="hover:text-ink hover:underline transition-colors">` + label + `</a>`
	}
	// The copyright line doubles as the site-wide route home — it is the
	// conventional place people look, and it covers deep-linked pages
	// (static content, account) that carry no other link back.
	return `<a href="/" preload="mousedown" class="hover:text-ink hover:underline transition-colors">© ` + year + ` Congopro</a> · ` +
		`<a href="https://t.me/+yzJqliLeudNkZjY0" target="_blank" rel="noopener noreferrer" class="hover:text-ink hover:underline transition-colors">Support</a> · ` +
		link("/help", "Aide") + " · " +
		link("/account", "Mon compte") + " · " +
		link("/privacy", "Confidentialité") + " · " +
		link("/terms", "Conditions")
}

// siteHeader is the compact brand bar for content pages that have no top
// bar of their own (help/privacy/terms). Deep links land on these pages
// from search engines and shared links, so they need a visible route back
// into the site rather than relying on the browser's back button.
func siteHeader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<header class=\"w-full border-b border-line bg-surface-raised\"><div class=\"max-w-3xl mx-auto px-4 sm:px-6 h-14 flex items-center\"><a href=\"/\" preload=\"mousedown\" class=\"flex items-center gap-2\" aria-label=\"Congopro Bridge — retour à l'accueil\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = brandMark("w-6 h-6 logo-a").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"wordmark font-sora font-semibold text-[17px]\"><span class=\"logo-a\">Congopro</span> <span class=\"logo-b\">Bridge.</span></span></a></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
